sonar.projectKey=Venkatesh-Nukala_sonarQube
sonar.organization=venkatesh-nukala

sonar.sources=.
sonar.tests=__tests__

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
